import { jsPDF } from "jspdf";
import type { FlowState } from "@/lib/flow";

/** Builds the GlowCast event-plan PDF client-side and triggers the download.
 *  Editorial layout: cover band, serif title, 2x2 look grid, swatch row,
 *  timeline with page-break handling. */

const W = 210;
const M = 18;
const PINK: [number, number, number] = [236, 72, 153];
const VIOLET: [number, number, number] = [139, 92, 246];
const INK: [number, number, number] = [131, 24, 67];
const GREY: [number, number, number] = [100, 116, 139];
const BG: [number, number, number] = [253, 242, 248];

export async function downloadPlanPdf(flow: FlowState) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 0;

  const footer = () => {
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GREY);
    doc.text(
      "Generated by GlowCast — skin analysis & virtual try-on powered by YouCam AI",
      W / 2,
      291,
      { align: "center" }
    );
  };

  const ensureRoom = (needed: number) => {
    if (y + needed > 280) {
      footer();
      doc.addPage();
      doc.setFillColor(...BG);
      doc.rect(0, 0, W, 297, "F");
      y = 20;
    }
  };

  const sectionTitle = (label: string) => {
    ensureRoom(16);
    doc.setFont("times", "bold");
    doc.setFontSize(15);
    doc.setTextColor(...INK);
    doc.text(label, M, y);
    doc.setDrawColor(...PINK);
    doc.setLineWidth(0.8);
    doc.line(M, y + 1.8, M + 24, y + 1.8);
    y += 9;
  };

  // ---------- Page background ----------
  doc.setFillColor(...BG);
  doc.rect(0, 0, W, 297, "F");

  // ---------- Cover band ----------
  doc.setFillColor(...INK);
  doc.rect(0, 0, W, 52, "F");
  doc.setFillColor(...PINK);
  doc.rect(0, 52, W, 1.6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(249, 168, 212);
  doc.text("G L O W C A S T", W / 2, 15, { align: "center" });

  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text(flow.eventTitle ?? "Your Big Day", W / 2, 28, { align: "center" });

  const dateLabel = flow.event
    ? new Date(flow.event.date + "T12:00:00").toLocaleDateString("en-US", {
        weekday: "long",
        month: "long",
        day: "numeric",
        year: "numeric",
      })
    : "";
  let meta = `${dateLabel}   ·   ${flow.event?.city ?? ""}`;
  if (flow.event?.weather) {
    meta += `   ·   ${flow.event.weather.condition}, ${flow.event.weather.tempMinC}–${flow.event.weather.tempMaxC}°C`;
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(251, 207, 232);
  doc.text(meta, W / 2, 37, { align: "center" });

  if (flow.globalScore != null) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(255, 255, 255);
    doc.text(`Skin score today: ${flow.globalScore}/100`, W / 2, 45.5, { align: "center" });
  }

  y = 66;

  // ---------- Colors ----------
  if (flow.palette && flow.palette.colors.length > 0) {
    sectionTitle(`Your Colors — ${flow.palette.season}`);
    const n = Math.min(8, flow.palette.colors.length);
    const gap = 4;
    const sw = (W - 2 * M - (n - 1) * gap) / n;
    flow.palette.colors.slice(0, n).forEach((hex, i) => {
      const x = M + i * (sw + gap);
      doc.setFillColor(hex);
      doc.roundedRect(x, y, sw, 16, 2.5, 2.5, "F");
      doc.setFontSize(6.8);
      doc.setFont("courier", "bold");
      doc.setTextColor(...GREY);
      doc.text(hex.toUpperCase(), x + sw / 2, y + 20.5, { align: "center" });
    });
    y += 27;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(...GREY);
    const desc = doc.splitTextToSize(flow.palette.description ?? "", W - 2 * M);
    doc.text(desc.slice(0, 3), M, y);
    y += desc.slice(0, 3).length * 4.4 + 9;
  }

  // ---------- Looks (2x2 grid) ----------
  if (flow.looks && flow.looks.length > 0) {
    const imgW = (W - 2 * M - 8) / 2;
    const imgH = imgW * (4 / 3) * 0.75; // slightly landscape-cropped cell
    sectionTitle("Your Looks");
    ensureRoom(imgH * 2 + 30);
    const looks = flow.looks.slice(0, 4);
    for (let i = 0; i < looks.length; i++) {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = M + col * (imgW + 8);
      const yy = y + row * (imgH + 14);
      try {
        doc.addImage(looks[i].url, "JPEG", x, yy, imgW, imgH, undefined, "MEDIUM");
        doc.setDrawColor(...PINK);
        doc.setLineWidth(0.4);
        doc.roundedRect(x, yy, imgW, imgH, 2, 2, "S");
      } catch {
        // skip unloadable image
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...INK);
      const label = doc.splitTextToSize(
        looks[i].style ? `${looks[i].label} — ${looks[i].style}` : looks[i].label,
        imgW
      );
      doc.text(label.slice(0, 1), x + imgW / 2, yy + imgH + 5, { align: "center" });
    }
    y += Math.ceil(looks.length / 2) * (imgH + 14) + 4;
  }

  // ---------- Skincare timeline ----------
  if (flow.skincarePlan && flow.skincarePlan.length > 0) {
    sectionTitle("Skincare Plan Until the Big Day");
    for (const e of flow.skincarePlan) {
      const lines: { tag: string; text: string }[] = [];
      if (e.am) lines.push({ tag: "AM", text: e.am });
      if (e.pm) lines.push({ tag: "PM", text: e.pm });
      if (e.tip) lines.push({ tag: "TIP", text: e.tip });
      ensureRoom(8 + lines.length * 5.2);

      doc.setFillColor(...PINK);
      doc.circle(M + 1.4, y - 1.3, 1.4, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(...INK);
      doc.text(e.label, M + 6, y);
      y += 5.4;

      for (const line of lines) {
        const wrapped = doc.splitTextToSize(line.text, W - 2 * M - 20);
        ensureRoom(wrapped.length * 4.4 + 1.5);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(...VIOLET);
        doc.text(line.tag, M + 6, y);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...GREY);
        doc.text(wrapped, M + 16, y);
        y += wrapped.length * 4.4 + 1.2;
      }
      y += 3.5;
    }
  }

  footer();
  doc.save("glowcast-event-plan.pdf");
}
